"""字段元数据：ref / virtual / trigger / encrypted / hints / select / legacy。"""

from __future__ import annotations

from .encrypted import (
    ENCRYPTED_PREFIX,
    EncryptedMarker,
    EncryptedValue,
    encrypted,
    is_encrypted_model_field,
)
from .hints import (
    ComponentHint,
    LegacyMarker,
    OptionHint,
    Select,
    UiHintMarker,
    UiHintsMap,
    build_ui_hints,
    iter_legacy_markers,
    legacy,
    select,
    ui,
)
from .ref import (
    NestedCollectionMarker,
    OnDeleteCallback,
    RefDeleteAction,
    RefField,
    Trigger,
    TriggerDecl,
    TriggerFieldBinding,
    Virtual,
    VirtualDecl,
    VirtualFieldBinding,
    VirtualFieldGetter,
    is_reactive_model_field,
    is_trigger_model_field,
    is_virtual_model_field,
    parse_field_path,
)

__all__ = [
    "ENCRYPTED_PREFIX",
    "EncryptedMarker",
    "EncryptedValue",
    "encrypted",
    "is_encrypted_model_field",
    "ComponentHint",
    "LegacyMarker",
    "OptionHint",
    "Select",
    "UiHintMarker",
    "UiHintsMap",
    "build_ui_hints",
    "iter_legacy_markers",
    "legacy",
    "select",
    "ui",
    "NestedCollectionMarker",
    "OnDeleteCallback",
    "RefDeleteAction",
    "RefField",
    "Trigger",
    "TriggerDecl",
    "TriggerFieldBinding",
    "Virtual",
    "VirtualDecl",
    "VirtualFieldBinding",
    "VirtualFieldGetter",
    "is_reactive_model_field",
    "is_trigger_model_field",
    "is_virtual_model_field",
    "parse_field_path",
]
