"""Sample plugin wheel builder for fake host tests.

Generates a minimal wheel with a controllable `Plugin` class. The
class is parameterized by a small JSON config so we can drive
pass / fail / leak / reload scenarios from a single test entry.

NOTE: The generated wheel is built in the scratch plugins_dir passed
by the harness. It does NOT touch the formal plugins/wheels/ tree.
"""
from __future__ import annotations

import importlib.metadata as importlib_metadata
import json
import os
import re
import shutil
import struct
import subprocess
import sys
import tempfile
import textwrap
import zipfile
from pathlib import Path
from typing import Iterable


PACKAGE_TPL = """\
# Auto-generated by build_fake_plugin_wheel.py — DO NOT MODIFY.
{module_doc}

# Embedded behaviour config (mutable, but frozen for testing).
FAKE_PLUGIN_CONFIG = {config_json!r}

# Bump to verify that reload_instance re-executes module top-level.
FAKE_PLUGIN_BUILD = {build!r}

from app.plugins.lifecycle import PluginLifecycle


class Plugin(PluginLifecycle):
    \"\"\"Fake plugin with controllable lifecycle hooks.\"\"\"

    def __init__(ctx_self, ctx):  # noqa: N805
        super().__init__(ctx)
        ctx_self.lifecycle_log = []
        ctx_self.started_event = "started"
        ctx_self.stopped_event = "stopped"
        # leak detector: register a listener so we can verify removal.
        # NOTE: PluginEventFacade.on() does not accept owner_plugin_name /
        # owner_instance_id kwargs — it injects them from the context.
        try:
            ctx_self._listener_id = ctx.event.on(
                "fake:probe",
                lambda payload: None,
                priority=0,
                scope="instance",
            )
        except Exception as e:  # pragma: no cover - harness should never fail here
            ctx_self._listener_id = None
            ctx_self._listener_error = repr(e)
        # Also register a global listener with owner_instance_id to test off_by_instance
        try:
            ctx_self._global_listener_id = ctx.event.on(
                "fake:probe_global",
                lambda payload: None,
                priority=0,
                scope="global",
            )
        except Exception as e:  # pragma: no cover - harness should never fail here
            ctx_self._global_listener_id = None
            ctx_self._global_listener_error = repr(e)

    async def on_load(self, ctx):
        self.lifecycle_log.append(("on_load", FAKE_PLUGIN_BUILD))
        if FAKE_PLUGIN_CONFIG.get("hook_on_load_raises"):
            raise RuntimeError("on_load intentionally raised")

    async def on_start(self):
        self.lifecycle_log.append(("on_start", FAKE_PLUGIN_BUILD))
        if FAKE_PLUGIN_CONFIG.get("hook_on_start_raises"):
            raise RuntimeError("on_start intentionally raised")

    async def on_stop(self, reason):
        self.lifecycle_log.append(("on_stop", reason))
        if FAKE_PLUGIN_CONFIG.get("hook_on_stop_raises"):
            raise RuntimeError("on_stop intentionally raised")

    async def on_unload(self):
        self.lifecycle_log.append(("on_unload", None))

    async def on_reload_prepare(self):
        self.lifecycle_log.append(("on_reload_prepare", FAKE_PLUGIN_BUILD))

    async def on_reload_commit(self):
        self.lifecycle_log.append(("on_reload_commit", FAKE_PLUGIN_BUILD))
"""


PYPROJECT_TPL = """\
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{distribution}"
version = "{version}"
description = "Fake plugin wheel built by harness for lifecycle tests"
requires-python = ">=3.10"
dependencies = []

[project.entry-points.{entry_group}]
{name} = "{module}:Plugin"
"""


def build_wheel(
    *,
    out_dir: Path,
    distribution: str,
    version: str,
    module: str,
    entry_group: str,
    entry_name: str,
    config: dict,
    build_id: str = "b1",
) -> Path:
    """Build a wheel into out_dir (which is the pypi site-packages).

    Uses the stdlib zipfile to avoid setuptools / build isolation. The
    resulting wheel is a valid PEP 427 wheel with METADATA, entry_points
    and a top-level module file.
    """
    out_dir = Path(out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    wheel_name = f"{distribution.replace('-', '_')}-{version}-py3-none-any.whl"
    wheel_path = out_dir / wheel_name

    # Module / package layout
    if "/" in module:
        # package form: module/.../leaf
        parts = module.split(".")
        pkg_dir = "/".join(parts)
    else:
        pkg_dir = module

    metadata = textwrap.dedent(f"""\
        Metadata-Version: 2.1
        Name: {distribution}
        Version: {version}
        Summary: fake plugin for blackbox tests
        Requires-Python: >=3.10
    """).strip() + "\n"

    entry_points_text = f"[{entry_group}]\n{entry_name} = {module}:Plugin\n"

    record = textwrap.dedent(f"""\
        {pkg_dir}/__init__.py,sha256=__SENTINEL__,{len(PACKAGE_TPL.format(module_doc='', config_json={}, build=''))}
        {distribution.replace('-', '_')}-{version}.dist-info/METADATA,sha256=__SENTINEL__,{len(metadata)}
        {distribution.replace('-', '_')}-{version}.dist-info/entry_points.txt,sha256=__SENTINEL__,{len(entry_points_text)}
        {distribution.replace('-', '_')}-{version}.dist-info/WHEEL,sha256=__SENTINEL__,100
        {distribution.replace('-', '_')}-{version}.dist-info/RECORD,,
    """).strip() + "\n"

    wheel_file_text = textwrap.dedent("""\
        Wheel-Version: 1.0
        Generator: fake-host-harness
        Root-Is-Purelib: true
        Tag: py3-none-any
    """).strip() + "\n"

    module_src = PACKAGE_TPL.format(
        module_doc="\"\"\"Fake plugin module.\"\"\"",
        config_json=config,
        build=build_id,
    )

    with zipfile.ZipFile(wheel_path, "w", zipfile.ZIP_DEFLATED) as zf:
        if "/" in pkg_dir:
            zf.writestr(f"{pkg_dir}/__init__.py", module_src)
        else:
            zf.writestr(f"{module}.py", module_src)
        zf.writestr(
            f"{distribution.replace('-', '_')}-{version}.dist-info/METADATA",
            metadata,
        )
        zf.writestr(
            f"{distribution.replace('-', '_')}-{version}.dist-info/entry_points.txt",
            entry_points_text,
        )
        zf.writestr(
            f"{distribution.replace('-', '_')}-{version}.dist-info/WHEEL",
            wheel_file_text,
        )
        zf.writestr(
            f"{distribution.replace('-', '_')}-{version}.dist-info/RECORD",
            record,
        )

    # Make sure the package directory exists in the actual site-packages
    # so importlib.metadata can read it without zipfile overhead. We
    # unpack ourselves for simplicity. We do NOT touch the formal
    # plugins/wheels/ dir — we only write to out_dir.
    _unpack_to_site(wheel_path, out_dir)
    return wheel_path


def _unpack_to_site(wheel_path: Path, site_dir: Path) -> None:
    """Unpack a wheel into a site-packages-like directory.

    PEP 427 mandates writing RECORD with sha256 and size, but Python's
    importlib.metadata is happy with RECORD present, even if the hashes
    are zero. We unpack into ``site_dir`` (not its parent) so the
    ``.dist-info`` and module files sit beside the wheel — which is the
    layout ``pip install --target`` and the real plugin host use.
    """
    import hashlib
    with zipfile.ZipFile(wheel_path) as zf:
        for member in zf.namelist():
            if member.endswith("/"):
                continue
            target = site_dir / member
            target.parent.mkdir(parents=True, exist_ok=True)
            data = zf.read(member)
            target.write_bytes(data)


def list_built_wheels(out_dir: Path) -> list[Path]:
    out_dir = Path(out_dir).resolve()
    return sorted(out_dir.glob("*.whl"))


def clear_built_wheels(out_dir: Path) -> None:
    """Remove every wheel and unpacked artifact previously produced for
    ``out_dir``.

    The site-packages layout (matching ``pip install --target``) places
    wheels, ``.dist-info`` directories and module files in a single
    directory. We nuke the entire directory and recreate it empty so the
    next build starts from a clean slate.
    """
    out_dir = Path(out_dir).resolve()
    if out_dir.exists():
        for entry in out_dir.iterdir():
            if entry.is_file():
                entry.unlink()
            elif entry.is_dir() and entry.name not in {"__pycache__"}:
                shutil.rmtree(entry, ignore_errors=True)
    out_dir.mkdir(parents=True, exist_ok=True)


def write_bad_manifest_wheel(*, out_dir: Path, distribution: str) -> Path:
    """A wheel that ships a malformed METADATA (truncated)."""
    out_dir = Path(out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    wheel_path = out_dir / f"{distribution.replace('-', '_')}-0.0.1-py3-none-any.whl"
    with zipfile.ZipFile(wheel_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(
            f"{distribution.replace('-', '_')}-0.0.1.dist-info/METADATA",
            "Metadata-Version: 2.1\nName: bad\n",  # missing Version etc.
        )
        zf.writestr(
            f"{distribution.replace('-', '_')}-0.0.1.dist-info/entry_points.txt",
            "[auto_mas.plugins]\n",
        )
    _unpack_to_site(wheel_path, out_dir)
    return wheel_path


def write_broken_module_wheel(*, out_dir: Path, distribution: str, module: str = "broken_plugin") -> Path:
    """A wheel whose module raises on import (to simulate bad plugin code)."""
    out_dir = Path(out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    wheel_path = out_dir / f"{distribution.replace('-', '_')}-0.0.1-py3-none-any.whl"
    module_src = "raise ImportError('broken_plugin intentionally fails to import')\n"
    entry_points_text = f"[auto_mas.plugins]\n{distribution.replace('-', '_')} = {module}:Plugin\n"
    metadata = f"Metadata-Version: 2.1\nName: {distribution}\nVersion: 0.0.1\n"
    with zipfile.ZipFile(wheel_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{module}.py", module_src)
        zf.writestr(f"{distribution.replace('-', '_')}-0.0.1.dist-info/METADATA", metadata)
        zf.writestr(
            f"{distribution.replace('-', '_')}-0.0.1.dist-info/entry_points.txt",
            entry_points_text,
        )
    _unpack_to_site(wheel_path, out_dir)
    return wheel_path
