/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { ADBScreenshotIn } from './models/ADBScreenshotIn';
export type { ADBScreenshotOut } from './models/ADBScreenshotOut';
export type { CheckImageAllIn } from './models/CheckImageAllIn';
export type { CheckImageAnyIn } from './models/CheckImageAnyIn';
export type { CheckImageIn } from './models/CheckImageIn';
export type { CheckImageOut } from './models/CheckImageOut';
export type { ClickImageIn } from './models/ClickImageIn';
export type { ClickOut } from './models/ClickOut';
export type { ClickTextIn } from './models/ClickTextIn';
export type { ComboBoxItem } from './models/ComboBoxItem';
export type { ComboBoxOut } from './models/ComboBoxOut';
export type { DeviceInfo } from './models/DeviceInfo';
export type { DispatchIn } from './models/DispatchIn';
export type { EmulatorConfig } from './models/EmulatorConfig';
export type { EmulatorConfig_Info } from './models/EmulatorConfig_Info';
export type { EmulatorConfigIndexItem } from './models/EmulatorConfigIndexItem';
export type { EmulatorCreateOut } from './models/EmulatorCreateOut';
export type { EmulatorDeleteIn } from './models/EmulatorDeleteIn';
export type { EmulatorGetIn } from './models/EmulatorGetIn';
export type { EmulatorGetOut } from './models/EmulatorGetOut';
export { EmulatorOperateIn } from './models/EmulatorOperateIn';
export type { EmulatorReorderIn } from './models/EmulatorReorderIn';
export type { EmulatorSearchOut } from './models/EmulatorSearchOut';
export type { EmulatorSearchResult } from './models/EmulatorSearchResult';
export type { EmulatorStatusOut } from './models/EmulatorStatusOut';
export type { EmulatorUpdateIn } from './models/EmulatorUpdateIn';
export type { GeneralConfig } from './models/GeneralConfig';
export type { GeneralConfig_Game } from './models/GeneralConfig_Game';
export type { GeneralConfig_Info } from './models/GeneralConfig_Info';
export type { GeneralConfig_Run } from './models/GeneralConfig_Run';
export type { GeneralConfig_Script } from './models/GeneralConfig_Script';
export type { GeneralUserConfig } from './models/GeneralUserConfig';
export type { GeneralUserConfig_Data } from './models/GeneralUserConfig_Data';
export type { GeneralUserConfig_Info } from './models/GeneralUserConfig_Info';
export type { GeneralUserConfig_Notify } from './models/GeneralUserConfig_Notify';
export type { GetPlanComboxIn } from './models/GetPlanComboxIn';
export { GetStageIn } from './models/GetStageIn';
export type { GlobalConfig } from './models/GlobalConfig';
export type { GlobalConfig_Function } from './models/GlobalConfig_Function';
export type { GlobalConfig_Notify } from './models/GlobalConfig_Notify';
export type { GlobalConfig_Start } from './models/GlobalConfig_Start';
export type { GlobalConfig_UI } from './models/GlobalConfig_UI';
export type { GlobalConfig_Update } from './models/GlobalConfig_Update';
export type { GlobalConfig_Voice } from './models/GlobalConfig_Voice';
export type { HistoryData } from './models/HistoryData';
export type { HistoryDataGetIn } from './models/HistoryDataGetIn';
export type { HistoryDataGetOut } from './models/HistoryDataGetOut';
export { HistoryIndexItem } from './models/HistoryIndexItem';
export { HistorySearchIn } from './models/HistorySearchIn';
export type { HistorySearchOut } from './models/HistorySearchOut';
export type { HTTPValidationError } from './models/HTTPValidationError';
export type { InfoOut } from './models/InfoOut';
export type { MaaConfig } from './models/MaaConfig';
export type { MaaConfig_Emulator } from './models/MaaConfig_Emulator';
export type { MaaConfig_Info } from './models/MaaConfig_Info';
export type { MaaConfig_Run } from './models/MaaConfig_Run';
export type { MaaEndConfig } from './models/MaaEndConfig';
export type { MaaEndConfig_Game } from './models/MaaEndConfig_Game';
export type { MaaEndConfig_Info } from './models/MaaEndConfig_Info';
export type { MaaEndConfig_Run } from './models/MaaEndConfig_Run';
export type { MaaEndPlanConfig } from './models/MaaEndPlanConfig';
export type { MaaEndPlanConfig_Info } from './models/MaaEndPlanConfig_Info';
export type { MaaEndPlanConfig_Item } from './models/MaaEndPlanConfig_Item';
export type { MaaEndUserConfig } from './models/MaaEndUserConfig';
export type { MaaEndUserConfig_Info } from './models/MaaEndUserConfig_Info';
export type { MaaEndUserConfig_Notify } from './models/MaaEndUserConfig_Notify';
export type { MaaEndUserConfig_Task } from './models/MaaEndUserConfig_Task';
export type { MaaPlanConfig } from './models/MaaPlanConfig';
export type { MaaPlanConfig_Info } from './models/MaaPlanConfig_Info';
export type { MaaPlanConfig_Item } from './models/MaaPlanConfig_Item';
export type { MaaUserConfig } from './models/MaaUserConfig';
export type { MaaUserConfig_Data } from './models/MaaUserConfig_Data';
export type { MaaUserConfig_Info } from './models/MaaUserConfig_Info';
export type { MaaUserConfig_Notify } from './models/MaaUserConfig_Notify';
export type { MaaUserConfig_Task } from './models/MaaUserConfig_Task';
export type { NoticeOut } from './models/NoticeOut';
export type { OCRScreenshotIn } from './models/OCRScreenshotIn';
export type { OCRScreenshotOut } from './models/OCRScreenshotOut';
export type { OutBase } from './models/OutBase';
export type { PlanCreateIn } from './models/PlanCreateIn';
export type { PlanCreateOut } from './models/PlanCreateOut';
export type { PlanConfigData } from './models/PlanConfigData';
export type { PlanDeleteIn } from './models/PlanDeleteIn';
export type { PlanGetIn } from './models/PlanGetIn';
export type { PlanGetOut } from './models/PlanGetOut';
export type { PlanIndexItem } from './models/PlanIndexItem';
export type { PlanReorderIn } from './models/PlanReorderIn';
export type { PlanUpdateIn } from './models/PlanUpdateIn';
export { PowerIn } from './models/PowerIn';
export { PowerOut } from './models/PowerOut';
export type { QueueConfig } from './models/QueueConfig';
export type { QueueConfig_Info } from './models/QueueConfig_Info';
export type { QueueCreateOut } from './models/QueueCreateOut';
export type { QueueDeleteIn } from './models/QueueDeleteIn';
export type { QueueGetIn } from './models/QueueGetIn';
export type { QueueGetOut } from './models/QueueGetOut';
export type { QueueIndexItem } from './models/QueueIndexItem';
export type { QueueItem } from './models/QueueItem';
export type { QueueItem_Info } from './models/QueueItem_Info';
export type { QueueItemCreateOut } from './models/QueueItemCreateOut';
export type { QueueItemDeleteIn } from './models/QueueItemDeleteIn';
export type { QueueItemGetIn } from './models/QueueItemGetIn';
export type { QueueItemGetOut } from './models/QueueItemGetOut';
export type { QueueItemIndexItem } from './models/QueueItemIndexItem';
export type { QueueItemReorderIn } from './models/QueueItemReorderIn';
export type { QueueItemUpdateIn } from './models/QueueItemUpdateIn';
export type { QueueReorderIn } from './models/QueueReorderIn';
export type { QueueSetInBase } from './models/QueueSetInBase';
export type { QueueUpdateIn } from './models/QueueUpdateIn';
export { ScriptCreateIn } from './models/ScriptCreateIn';
export type { ScriptCreateOut } from './models/ScriptCreateOut';
export type { ScriptDeleteIn } from './models/ScriptDeleteIn';
export type { ScriptFileIn } from './models/ScriptFileIn';
export type { ScriptGetIn } from './models/ScriptGetIn';
export type { ScriptGetOut } from './models/ScriptGetOut';
export { ScriptIndexItem } from './models/ScriptIndexItem';
export type { ScriptReorderIn } from './models/ScriptReorderIn';
export type { ScriptUpdateIn } from './models/ScriptUpdateIn';
export type { ScriptUploadIn } from './models/ScriptUploadIn';
export type { ScriptUrlIn } from './models/ScriptUrlIn';
export type { SettingGetOut } from './models/SettingGetOut';
export type { SettingUpdateIn } from './models/SettingUpdateIn';
export type { SrcConfig } from './models/SrcConfig';
export type { SrcConfig_Emulator } from './models/SrcConfig_Emulator';
export type { SrcConfig_Info } from './models/SrcConfig_Info';
export type { SrcConfig_Run } from './models/SrcConfig_Run';
export type { SrcUserConfig } from './models/SrcUserConfig';
export type { SrcUserConfig_Data } from './models/SrcUserConfig_Data';
export type { SrcUserConfig_Info } from './models/SrcUserConfig_Info';
export type { SrcUserConfig_Notify } from './models/SrcUserConfig_Notify';
export type { SrcUserConfig_Stage } from './models/SrcUserConfig_Stage';
export { TaskCreateIn } from './models/TaskCreateIn';
export type { TaskCreateOut } from './models/TaskCreateOut';
export type { TimeSet } from './models/TimeSet';
export type { TimeSet_Info } from './models/TimeSet_Info';
export type { TimeSetCreateOut } from './models/TimeSetCreateOut';
export type { TimeSetDeleteIn } from './models/TimeSetDeleteIn';
export type { TimeSetGetIn } from './models/TimeSetGetIn';
export type { TimeSetGetOut } from './models/TimeSetGetOut';
export type { TimeSetIndexItem } from './models/TimeSetIndexItem';
export type { TimeSetReorderIn } from './models/TimeSetReorderIn';
export type { TimeSetUpdateIn } from './models/TimeSetUpdateIn';
export type { ToolsConfig } from './models/ToolsConfig';
export type { ToolsConfig_ArknightsPC } from './models/ToolsConfig_ArknightsPC';
export type { ToolsGetOut } from './models/ToolsGetOut';
export type { ToolsUpdateIn } from './models/ToolsUpdateIn';
export type { UpdateCheckIn } from './models/UpdateCheckIn';
export type { UpdateCheckOut } from './models/UpdateCheckOut';
export type { UserCreateOut } from './models/UserCreateOut';
export type { UserDeleteIn } from './models/UserDeleteIn';
export type { UserGetIn } from './models/UserGetIn';
export type { UserGetOut } from './models/UserGetOut';
export type { UserInBase } from './models/UserInBase';
export { UserIndexItem } from './models/UserIndexItem';
export type { UserReorderIn } from './models/UserReorderIn';
export type { UserSetIn } from './models/UserSetIn';
export type { UserUpdateIn } from './models/UserUpdateIn';
export type { ValidationError } from './models/ValidationError';
export type { VersionOut } from './models/VersionOut';
export type { Webhook } from './models/Webhook';
export type { Webhook_Data } from './models/Webhook_Data';
export type { Webhook_Info } from './models/Webhook_Info';
export type { WebhookCreateOut } from './models/WebhookCreateOut';
export type { WebhookDeleteIn } from './models/WebhookDeleteIn';
export type { WebhookGetIn } from './models/WebhookGetIn';
export type { WebhookGetOut } from './models/WebhookGetOut';
export type { WebhookInBase } from './models/WebhookInBase';
export type { WebhookIndexItem } from './models/WebhookIndexItem';
export type { WebhookReorderIn } from './models/WebhookReorderIn';
export type { WebhookTestIn } from './models/WebhookTestIn';
export type { WebhookUpdateIn } from './models/WebhookUpdateIn';
export type { WSClearHistoryIn } from './models/WSClearHistoryIn';
export type { WSClientAuthIn } from './models/WSClientAuthIn';
export type { WSClientConnectIn } from './models/WSClientConnectIn';
export type { WSClientCreateIn } from './models/WSClientCreateIn';
export type { WSClientCreateOut } from './models/WSClientCreateOut';
export type { WSClientDisconnectIn } from './models/WSClientDisconnectIn';
export type { WSClientListOut } from './models/WSClientListOut';
export type { WSClientRemoveIn } from './models/WSClientRemoveIn';
export type { WSClientSendIn } from './models/WSClientSendIn';
export type { WSClientSendJsonIn } from './models/WSClientSendJsonIn';
export type { WSClientStatusIn } from './models/WSClientStatusIn';
export type { WSClientStatusOut } from './models/WSClientStatusOut';
export type { WSCommandsOut } from './models/WSCommandsOut';
export type { WSMessageHistoryOut } from './models/WSMessageHistoryOut';

export { Service } from './services/Service';
export { ActionService } from './services/ActionService';
export { AddService } from './services/AddService';
export { DeleteService } from './services/DeleteService';
export { GetService } from './services/GetService';
export { OcrService } from './services/OcrService';
export { UpdateService } from './services/UpdateService';
export { WebSocketService } from './services/WebSocketService';
