export { apiClient, apiRuntime } from './runtime'
export {
  HISTORY_SEARCH_MODE,
  POWER_SIGNAL,
  SCRIPT_CREATE_TYPE,
  STAGE_QUERY_TYPE,
  TASK_CREATE_MODE,
} from './constants'
export type {
  HistorySearchMode,
  PowerSignal,
  ScriptCreateType,
  StageQueryType,
  TaskCreateMode,
} from './constants'

export { dispatchApi } from './gateways/dispatch'
export { emulatorApi } from './gateways/emulator'
export { historyApi } from './gateways/history'
export { infoApi } from './gateways/info'
export { ocrApi } from './gateways/ocr'
export { planApi } from './gateways/plan'
export { pluginApi } from './gateways/plugin'
export { queueApi, queueItemApi, timeSetApi } from './gateways/queue'
export { scriptApi, userApi } from './gateways/script'
export { settingApi, webhookApi } from './gateways/setting'
export { toolsApi } from './gateways/tools'
export { updateApi } from './gateways/update'
export { wsDebugApi } from './gateways/wsDebug'

export type {
  PluginInstance,
  PluginMutationOut,
  PluginsGetOut as PluginGetOut,
  PluginRuntimeState,
  PluginSchemaField,
} from './gateways/plugin'

export type {
  AdbScreenshotIn,
  AdbScreenshotOut,
  ComboBoxItem,
  DispatchIn,
  EmulatorActionBody,
  EmulatorConfigIndexItem,
  EmulatorDetailOut,
  EmulatorGetOut,
  EmulatorRead,
  EmulatorSearchOut,
  EmulatorSearchResult,
  GeneralConfig,
  GeneralUserConfig,
  GetStageIn,
  GlobalConfigRead,
  HistoryData,
  HistoryDataGetIn,
  HistoryDataGetOut,
  HistoryIndexItem,
  HistorySearchIn,
  HttpValidationError,
  IndexOrderPatch,
  InfoOut,
  InfrastructureImportBody,
  MaaConfig,
  MaaEndConfig,
  MaaEndUserConfig,
  MaaPlanDayPatch,
  MaaPlanDayRead,
  MaaPlanInfoPatch,
  MaaPlanInfoRead,
  MaaPlanPatch,
  MaaPlanRead,
  MaaUserConfig,
  NoticeOut,
  OcrScreenshotIn,
  OcrScreenshotOut,
  OutBase,
  PlanCreateIn,
  PlanCreateOut,
  PlanDetailOut,
  PlanGetOut,
  PlanIndexItem,
  PlanUpdateBody,
  PowerIn,
  PowerOut,
  QueueCreateOut,
  QueueDetailOut,
  QueueGetOut,
  QueueIndexItem,
  QueueItemCreateOut,
  QueueItemDetailOut,
  QueueItemGetOut,
  QueueItemIndexItem,
  QueueItemRead,
  QueueRead,
  ScriptCreateIn,
  ScriptCreateOut,
  ScriptDetailOut,
  ScriptFileBody,
  ScriptGetOut,
  ScriptIndexItem,
  ScriptPatchBody,
  ScriptUploadBody,
  ScriptUrlBody,
  SrcConfig,
  SrcUserConfig,
  TaskCreateIn,
  TimeSetCreateOut,
  TimeSetDetailOut,
  TimeSetGetOut,
  TimeSetIndexItem,
  TimeSetRead,
  ToolsConfigRead,
  ToolsConfigReadArknightsPc,
  UpdateCheckIn,
  UpdateCheckOut,
  UserCreateOut,
  UserDetailOut,
  UserGetOut,
  UserIndexItem,
  UserPatchBody,
  ValidationError,
  VersionOut,
  WebhookCreateOut,
  WebhookDetailOut,
  WebhookGetOut,
  WebhookIndexItem,
  WebhookRead,
  WsClearHistoryIn,
  WsClientAuthIn,
  WsClientConnectIn,
  WsClientCreateIn,
  WsClientCreateOut,
  WsClientDisconnectIn,
  WsClientListOut,
  WsClientRemoveIn,
  WsClientSendIn,
  WsClientSendJsonIn,
  WsClientStatusIn,
  WsClientStatusOut,
  WsCommandsOut,
  WsMessageHistoryOut,
} from './generated'
